title: Sheng Shi
description: Sheng Shi's personal website and blog.
url: "https://mikuase-shi.github.io"
baseurl: ""
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /blog/:title/
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
